### ISSUE TITLE
Examples still available?

### ISSUE THREAD

**Issue by jesseward** [fotcorn/Python-C64-Emulator#1]
neat project. Do you happen to have either of the following examples available ?

```
main.py:    loader.load_file('/home/corn/Projekte/6502emu/examples/conditional_jumps/task1')
programloader.py:    loader.load_file('/home/corn/Projekte/6502emu/examples/asm/count10')
```

**Comment by fotcorn** [comment]
I've added some example programs in the examples/ directory. Keep in mind that many instructions are not yet implemented.
